trigger: none

pool:
  name: akhileshinfosys

variables:
  serviceConnection: 'akhileshapp'
  resourceGroup: 'tikoo'
  storageAccount: 'tikoostorage789'
  containerName: 'rahulchor'
  tfStateKey: 'st.tf'

stages:

# ---------------- FORMAT ----------------
- stage: FORMAT
  displayName: "Terraform Format"
  jobs:
  - job: fmt
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: '1.5.7'

    - script: terraform fmt -recursive
      displayName: "Auto Format Fix"

# ---------------- VALIDATE ----------------
- stage: VALIDATE
  displayName: "Init & Validate"
  dependsOn: FORMAT
  jobs:
  - job: validate
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: '1.5.7'

    - task: TerraformTask@5
      displayName: "Terraform Init"
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: $(serviceConnection)
        backendAzureRmResourceGroupName: $(resourceGroup)
        backendAzureRmStorageAccountName: $(storageAccount)
        backendAzureRmContainerName: $(containerName)
        backendAzureRmKey: $(tfStateKey)

    - task: TerraformTask@5
      displayName: "Terraform Validate"
      inputs:
        provider: 'azurerm'
        command: 'validate'

# ---------------- SECURITY ----------------
- stage: SECURITY
  displayName: "Security Scan (tfsec)"
  dependsOn: VALIDATE
  jobs:
  - job: tfsec_scan
    steps:
    - script: |
        curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
        tfsec .
      displayName: "Run tfsec scan"
      continueOnError: false

# ---------------- PLAN ----------------
- stage: PLAN
  displayName: "Terraform Plan"
  dependsOn: SECURITY
  jobs:
  - job: plan
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: '1.5.7'

    - task: TerraformTask@5
      displayName: "Terraform Init"
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: $(serviceConnection)
        backendAzureRmResourceGroupName: $(resourceGroup)
        backendAzureRmStorageAccountName: $(storageAccount)
        backendAzureRmContainerName: $(containerName)
        backendAzureRmKey: $(tfStateKey)

    - task: TerraformTask@5
      displayName: "Terraform Plan"
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: $(serviceConnection)

# ---------------- APPROVAL ----------------
- stage: APPROVAL
  displayName: "Manual Approval"
  dependsOn: PLAN
  jobs:
  - job: approval
    pool: server
    steps:
    - task: ManualValidation@0
      inputs:
        instructions: "Approve Terraform deployment"
        timeoutInMinutes: 60

# ---------------- APPLY ----------------
- stage: APPLY
  displayName: "Terraform Apply"
  dependsOn: APPROVAL
  jobs:
  - job: apply
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: '1.5.7'

    - task: TerraformTask@5
      displayName: "Terraform Init"
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: $(serviceConnection)
        backendAzureRmResourceGroupName: $(resourceGroup)
        backendAzureRmStorageAccountName: $(storageAccount)
        backendAzureRmContainerName: $(containerName)
        backendAzureRmKey: $(tfStateKey)

    - task: TerraformTask@5
      displayName: "Terraform Apply"
      inputs:
        provider: 'azurerm'
        command: 'apply'
        environmentServiceNameAzureRM: $(serviceConnection)
        args: '-auto-approve'